### ISSUE TITLE
Reduce logging noise

### ISSUE THREAD

**Issue by samsrabin** [ESCOMP/MOSART#104]
As discussed at [CSEG meeting 2024-06-18](https://docs.google.com/document/d/186U6-dt_wWZZGU9NzYQ5zNlMnpx9XX6oweuTXzQY-oo/edit#heading=h.gjot13e7ggkb), reducing unnecessary messaging is a CSEG goal for CESM3.

The `mosart decomp info` message can probably be changed to only show if the XML `DEBUG` setting is true? (By wrapping in `#ifndef NDEBUG`/`#endif`)

**Comment by ekluzek** [comment]
@slevis-lmwg this is a simple thing that could be done with the other mosart work.
