### ISSUE TITLE
Change MOSART tests to all be Clm60?

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/MOSART#107]
The MOSART tests are currently almost all Clm50, with the CESM3.0 release and Clm60 being available I think they should be updated to all be Clm60. Testing for different CLM versions likely should just be part of the CLM testing, and MOSART tests should just be using the latest CLM physics option.

@slevis-lmwg do you have an opinion on this?

**Comment by slevis-lmwg** [comment]
That sounds reasonable to me.
