### ISSUE TITLE
do_rtm=FALSE is not working with NUOPC

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/MOSART#47]
The mosartOff testmod seems to be failing when run with NUOPC.

I'm testing this what will be mosart1_0_44, with future ctsm5.1.dev062, but I think this is a problem with the previous version as well.

The test

SMS_Ld1_D_Vnuopc.f10_f10_mg37.I2000Clm50BgcCru.cheyenne_intel.mosart-mosartOff

fails.

**Comment by ekluzek** [comment]
OK it does work when MOSART_MODE is set to NULL. This is because the driver then turns MOSART completely off and uses a stub in place of MOSART.

**Comment by mvertens** [comment]
@ekluzek - I agree that setting MOSART_MODE to NULL is the right solution for this.
