### ISSUE TITLE
REST_OPTION=nsteps not working correctly

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/MOSART#89]
In the nuopc cap.  Please see issue https://github.com/ESCOMP/CMEPS/issues/443

**Comment by ekluzek** [comment]
Thanks for pointing this out @jedwards4b

@slevis-lmwg you and I should discuss this briefly.

We should make sure we have testing for this. I think we have tests that run long enough, but we likely we haven't checked to ensure the correct restart files are being written.

**Comment by wwieder** [comment]
Can this be resolved and merged with #76 or the PR for #92?

**Comment by jedwards4b** [comment]
@wwieder it was something I plan to address prior to cesm3.0 release, it requires changes in cmeps and may or may not require changes in other components including mosart.

**Comment by ekluzek** [comment]
I think this was resolved just within CMEPS, so I'm marking as completed.
