### ISSUE TITLE
"if (ierr /= PIO_NOERR)" will not be invoked unless PIO_BCAST_ERROR is explicitly set

### ISSUE THREAD

**Issue by slevis-lmwg** [ESCOMP/MOSART#93]
Unless PIO_BCAST_ERROR is explicitly set the pio error will be handled in the pio library and the code will not return to this location with an error.

_Originally posted by @jedwards4b in https://github.com/ESCOMP/MOSART/pull/76#discussion_r1438918283_

**Comment by slevis-lmwg** [comment]
Another relevant comment:
https://github.com/ESCOMP/MOSART/pull/76#discussion_r1438918395

**Comment by mvertens** [comment]
This was indeed a problem in the refactored code and I have fixed it.
