### ISSUE TITLE
Change namelist items to remove "rtm" in the names of namelist variables

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/MOSART#98]
namelist variables have rtm in the name. This is similar to #97 except here I'm just mentioning namelist variables, which is important to note since they are using facing.

The main reason for having RTM in the names of namelist variables goes back to when RTM was a subroutine call from within CLM. So this is removing an old feature that isn't needed anymore.

This is done in #76

**Comment by ekluzek** [comment]
@mvertens I would've had a preference for the rtmhist_* to be changed to hist_* so that all history variables are grouped together. But, that is a small nitpick and we don't want to have to redo testing, so we'll leave it like it is, unless someone really wants to do that on their own.

**Comment by mvertens** [comment]
@ekluzek - I agree. I will change this in the new PR.
