### ISSUE TITLE
Add a new mosart_noresm testlist

### ISSUE THREAD

**Issue by ekluzek** [ESCOMP/MOSART#99]
For use by NorESM they want to have a mosart_noresm testlist for their use on the Norwegian machine betzy.

This is done in #76

**Comment by ekluzek** [comment]
@mvertens since the mosart_noresm testlist just adds betzy -- is there a need for the new name? You could just use the "mosart" test category name, so we have fewer testlists, but just configure the testlist for betzy to be whatever NorESM wants it to be. NorESM folks will be the only ones that run on betzy, so you'd have total control of the testlist for that machine.

But, I also realize that having _noresm in the test category name might be important for the NorESM workflow. So it's fine either way. I have a slight preference for one test category name, but most important is what you want for your workflow.

**Comment by mvertens** [comment]
@ekluzek - good point about the testname. At this point I'd like to keep it separate in case we do have different testing we want to do.
